# Generated by Django 3.1.5 on 2021-05-10 20:47

from django.contrib.postgres.operations import UnaccentExtension
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        UnaccentExtension()
    ]
